@baseUrl = http://localhost:3333

# @name create_user
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "John Doe",
  "cpf": "28725945075",
  "password": "123456"
}

###

# @name authenticate_user
POST {{baseUrl}}/users/sessions
Content-Type: application/json

{
  "cpf": "28725945075",
  "password": "123456"
}